# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 06:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasteredWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64, null=True)),
                ('profile', models.ManyToManyField(to='TermBuilder.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='masteredwords',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TermBuilder.Profile'),
        ),
        migrations.AddField(
            model_name='masteredwords',
            name='words',
            field=models.ManyToManyField(to='TermBuilder.Word'),
        ),
        migrations.AddField(
            model_name='definition',
            name='word',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='TermBuilder.Word'),
        ),
    ]
