# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TermBuilder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='profile',
        ),
    ]
