# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TermBuilder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='wordList',
        ),
        migrations.AddField(
            model_name='profile',
            name='definitions',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='words',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
