# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TermBuilder', '0002_remove_word_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='profile',
            field=models.ManyToManyField(to='TermBuilder.Profile'),
        ),
    ]
