# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TermBuilder', '0002_auto_20170701_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='definition',
            name='word',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TermBuilder.Word'),
        ),
    ]
