# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TermBuilder', '0003_auto_20170701_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='definitions',
        ),
        migrations.AlterField(
            model_name='profile',
            name='words',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TermBuilder.Word'),
        ),
    ]
