# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TermBuilder', '0004_auto_20170701_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='words',
        ),
        migrations.AddField(
            model_name='word',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TermBuilder.Profile'),
        ),
    ]
