# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TermBuilder', '0004_profile_lasttestscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currentTestScore',
            field=models.IntegerField(default=0),
        ),
    ]
