# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TermBuilder', '0005_auto_20170701_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='value',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='definition',
            name='word',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='TermBuilder.Word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='value',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
