# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TermBuilder', '0005_profile_currenttestscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='totalTestPassed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='totalTestTaken',
            field=models.IntegerField(default=0),
        ),
    ]
